### DISCUSSION TITLE
Default DB_CONNECTION_ARGS

### DISCUSSION THREAD

**Discussion by immauss** [quay/quay#2249] [General]
As a first-time user of quay, I started with the "Getting Started" in the docs. 

There were some minor differences in the existing docs from the current interface, but nothing I couldn't resolve easily. However, when I started the container, it would die with:
```
psycopg2.ProgrammingError: invalid dsn: invalid connection option "keepalivescount"
```

It seems something has changed in the DB configuration??? 
In order to get the container to start, I had to make the following changes to the config:

Original:
```
DB_CONNECTION_ARGS:
    keepalives: 0
    keepalivescount: 0
    keepalivesidle: 0
    keepalivesinterval: 0
    sslcompression: 0
    tcpusertimeout: 0
```
Working:
```
DB_CONNECTION_ARGS:
    keepalives: 0
    sslcompression: 0
```

Each of the items removed from that section caused the same "invalid dsn:" error.
