### DISCUSSION TITLE
S3 Bucket connection error due to false reassembly

### DISCUSSION THREAD

**Discussion by HammerMeetNail** [quay/quay#2990] [General]
Raising on behalf of [hu1buerger@gmail.com](mailto:hu1buerger@gmail.com)
See https://issues.redhat.com/browse/PROJQUAY-7415

**Comment by michaelalang** [comment]
if this is still an issue, the configuration provided explains why the connection to an onPrem S3 Storage is not happening

```
DISTRIBUTED_STORAGE_CONFIG:
  default:
    - S3Storage
    - host: s3.mydomain.com
       s3_access_key: ----
       s3_bucket: quay-registry-images
       s3_secret_key: ------
       storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
  - default
```

the `S3Storage` class i meant to connect to AWS only. For local S3 Storage systems (like Ceph/MinIO/NetApp/...) the `RadosGWStorage` shall be used which goes with following parameters 

```
DISTRIBUTED_STORAGE_CONFIG:
  default:
    - RadosGWStorage
    - hostname: s3.mydomain.com
       access_key: ----
       bucket_name: quay-registry-images
       secret_key: ------
       port: 9000  # MinIO example
       is_secure: false  # MinIO example
       region_name: us-east-1 # version 3.12+ only omit if earlier version is used
       signature_version=v4 # version 3.12+ only omit if earlier version is used
    storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
  - default 
DISTRIBUTED_STORAGE_PREFERENCE:
  - default
```

hope that helps if it's still necessary
