### DISCUSSION TITLE
Invalid configuration by `config secret`

### DISCUSSION THREAD

**Discussion by nandi95** [quay/quay#3182] [General]
I just used the config wizard to set up quay

```
config:
    command: config secret
    image: quay.io/projectquay/quay:latest
    ports:
      - 8080:8080
    volumes:
      - app_config:/conf/stack
```

The generated config that I download has some invalid `DB_CONNECTION_ARGS` options for the postgres version I'm using (16)
For example: https://github.com/quay/quay/discussions/2249
The driver for peewee ORM, psycopg2 is passing the keys as is to postgres and the keys have changed. They are now using underscore so `keepalivescount` becomes `keepalives_count`

Perhaps consider adding a database version select in the wizard and generate based on that?

See options at:
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS
