### DISCUSSION TITLE
docker login Error response from daemon: Get "http://IPADDRESS/v2/": unauthorized: authGroup.Verify

### DISCUSSION THREAD

**Discussion by JustGitting** [quay/quay#3957] [Q&A]
Hi,

I'm stuck with a problem logging into the Quay instance via docker login CLI.

I've setup a Quay instance using docker compose on a linux machine (IP 192.168.102.165).

```bash
linux host $ cat docker-compose-quay.yml
```

```yaml
services:
  quay-db:
    container_name: quay-db
    image: postgres:13.21
    environment:
      POSTGRES_USER: "quaydbuser"
      POSTGRES_PASSWORD: "quaydbpassword"
      POSTGRES_DB: "quay"
    volumes:
      - "./quay/postgresql/init/pg_bootstrap.sql:/docker-entrypoint-initdb.d/pg_bootstrap.sql"
      - "./quay/postgresql/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quaydbuser -d quay"]
      interval: 10s
      timeout: 9s
      retries: 3
      start_period: 10s

  redis:
    container_name: quay-redis
    image: redis:latest
    ports:
      - "6379:6379"

  quay:
    container_name: quay
    # image: quay.io/projectquay/quay:latest # Very old version 3.8.1
    image: quay.io/projectquay/quay:3.14.1
    volumes:
      - "./quay/config:/conf/stack"
      - "./quay/storage:/datastorage"
    ports:
		# Another service is using 8080
      - "9080:8080"  
      - "9443:8443"
    environment:
      DEBUGLOG: "true"
      IGNORE_VALIDATION: "true"
    depends_on:
      quay-db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
```

The Quay config.yaml:

`linux host $ cat ./quay/config/config.yaml`

```yaml
SUPER_USERS:
- admin
- user1
AUTHENTICATION_TYPE: Database
BITTORRENT_FILENAME_PEPPER: 0ee18f90-5b6d-42d2-ab5e-ec9fcd846272
BUILDLOGS_REDIS:
  host: quay-redis
  port: 6379
DATABASE_SECRET_KEY: '30060361640793187613697366923211113205676925445650250274752125083971638376224'
DB_URI: postgresql://quaydbuser:quaydbpassword@quay-db/quay
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
  default:
  - LocalStorage
  - storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
- default
FEATURE_MAILING: false
LOG_ARCHIVE_LOCATION: default
PREFERRED_URL_SCHEME: http
REGISTRY_TITLE: DSU Quay
REGISTRY_TITLE_SHORT: DSU Quay
SERVER_HOSTNAME: 192.168.102.165
SETUP_COMPLETE: true
SIGNING_ENGINE: gpg2
TAG_EXPIRATION_OPTIONS:
- 0s
- 1d
- 1w
- 2w
- 4w
TEAM_RESYNC_STALE_TIME: 60m
TESTING: false
USERFILES_LOCATION: default
USERFILES_PATH: userfiles/
USER_EVENTS_REDIS:
  host: quay-redis
  port: 6379

```

To turn off the requirement for a secure connection, I added the following directive to both the host and client Linux machines.

```
$ sudo nano /etc/docker/daemon.json 

{
  "insecure-registries": [
     "192.168.102.165:9080"
  ]
}
```

Start docker compose.

`linux host $ sudo docker compose -f docker-compose-quay.yml -p quay up -d`

Using Firefox in Windows 10, I visit http://192.168.102.165:9080 and register the user _user1_ with a password (no need to verify email as I've disabled it in the Quay config.yaml file).

Once logged in via the web GUI with _user1_ account, I create the repo "testrepo" which is successful.

In account settings, under the "Docker CLI Password" section, I "Generate Encrypted Password" and copy the key value to the file ./quay/secrets.txt on the linux client (IP 192.168.102.162).

I attempt to log into Quay via docker login from a linux client (IP 192.168.102.162) as below.

linux client $ cat ./quay/secrets.txt | sudo docker -l debug login --username user1 --password-stdin 192.168.102.165:9080
Error response from daemon: Get "http://192.168.102.165:9080/v2/": unauthorized: authGroup.Verify

Relevant logs:

```
linux host $ sudo docker compose -p quay logs 
...
quay        | exportactionlogsworker stdout | 2025-05-26 04:36:52,603 [67] [DEBUG] [apscheduler.scheduler] Looking for jobs to run
quay        | exportactionlogsworker stdout | 2025-05-26 04:36:52,604 [67] [DEBUG] [apscheduler.scheduler] Next wakeup is due at 2025-05-26 04:37:42.601883+00:00 (in 49.997422 seconds)
quay        | exportactionlogsworker stdout | 2025-05-26 04:36:52,604 [67] [INFO] [apscheduler.executors.default] Running job "QueueWorker.run_watchdog (trigger: interval[0:01:00], next run at: 2025-05-26 04:37:52 GMT)" (scheduled at 2025-05-26 04:36:52.603149+00:00)
quay        | exportactionlogsworker stdout | 2025-05-26 04:36:52,605 [67] [DEBUG] [workers.queueworker] Running watchdog.
quay        | exportactionlogsworker stdout | 2025-05-26 04:36:52,605 [67] [INFO] [apscheduler.executors.default] Job "QueueWorker.run_watchdog (trigger: interval[0:01:00], next run at: 2025-05-26 04:37:52 GMT)" executed successfully
quay        | nginx stdout | 192.168.102.162 (-) - - [26/May/2025:04:36:54 +0000] "\x16\x03\x01\x05\xA4\x01\x00\x05\xA0\x03\x03%\xFD]\xAE\xE8~\x924}q\x0B\xC9\xD7\x8E\x9B\xC6\xD5\x09\xE5U,\x10t\xEC\xFF\xAC\x9B\xA8\x95p\xB5\x86 \xA0\xA5\x8F\x03m#\xF8\xFD\xE5\x09Jw\xD5\xAD\x93\x9Eg\xA6\xD6\xF3\xC5T31YG}\xD9\x95\xCD]2\x00\x16\xC0+\xC0/\xC0,\xC00\xC0\x09\xC0\x13\xC0" 400 157 "-" "-" (0.001 0 -)
quay        | gunicorn-registry stdout | 2025-05-26 04:36:54,766 [292] [DEBUG] [app] Starting request: urn:request:724a124c-8070-4e99-a8b2-3df99e535a2e (/v2/) {'X-Forwarded-For': '192.168.102.162'}
quay        | gunicorn-registry stdout | 2025-05-26 04:36:54,766 [292] [DEBUG] [auth.registry_jwt_auth] Called with params: (), {}
quay        | gunicorn-registry stdout | 2025-05-26 04:36:54,767 [292] [DEBUG] [auth.registry_jwt_auth] No auth header.
quay        | gunicorn-registry stdout | 2025-05-26 04:36:54,768 [292] [DEBUG] [app] Ending request: urn:request:724a124c-8070-4e99-a8b2-3df99e535a2e (/v2/) {'endpoint': 'v2.v2_support_enabled', 'request_id': 'urn:request:724a124c-8070-4e99-a8b2-3df99e535a2e', 'remote_addr': '192.168.102.162', 'http_method': 'GET', 'original_url': 'http://192.168.102.165/v2/', 'path': '/v2/', 'parameters': {}, 'json_body': None, 'confsha': 'a1a37217', 'user-agent': 'docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/6.1.0-32-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \\(linux\\))'}
quay        | gunicorn-registry stdout | 2025-05-26 04:36:54,769 [292] [INFO] [gunicorn.access] 192.168.102.162 - - [26/May/2025:04:36:54 +0000] "GET /v2/ HTTP/1.1" 401 4 "-" "docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/6.1.0-32-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \(linux\))"
quay        | nginx stdout | 192.168.102.162 (-) - - [26/May/2025:04:36:54 +0000] "GET /v2/ HTTP/1.1" 401 4 "-" "docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/6.1.0-32-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \x5C(linux\x5C))" (0.006 236 0.005)
```

I've searched for the error message, but I've not found anything. Any suggestions welcome.

Is this because I've turned off email verification (authGroup.Verify??) of the account. Or is it something else?
